secrets:
    dozzle_cert:
        file: ENC[AES256_GCM,data:F6/WbaWujcZJxysMnHsPLGQ=,iv:piWKsxtpnHyCVX9qN4anvbwayzaL9eG8MzWaGCB0xKg=,tag:lB+vhuLb/NYYZIihk52vnQ==,type:str]
    dozzle_key:
        file: ENC[AES256_GCM,data:VSJ1PFiRQDWPan0t+7LjMw==,iv:Dy+hX2J5dqvtyjXtvqZPZZIp7NrK/mdlQpABBwCAcAw=,tag:1oSER81Q2XSYjLUs2ScV+Q==,type:str]
services:
    dozzle-agent:
        command: ENC[AES256_GCM,data:tspRx4Y=,iv:xqvCLJbg/5bbCTe1dAueyqFKzIvJC+kfgF4wNacF0uk=,tag:RLbWu0Ebi7Z8c5evAGjBdg==,type:str]
        environment:
            DOZZLE_HOSTNAME: ENC[AES256_GCM,data:VHFJDhz2,iv:OUBQPLzPKZfFl7rPyDEO5N5kc22/EtO8q1WbFwwGbMs=,tag:D/4TgkKKJRv/ZDhq5kSFAQ==,type:str]
        image: ENC[AES256_GCM,data:KvMQpYwyiOhUD2sU2PUV1lY0SdcL+w==,iv:rCHJyILZc2LOLGBzR6lb1H78NByEpVYd2Jw+slPGVkg=,tag:aR1y66fIC/jgK1eyG28jJQ==,type:str]
        ports:
            - ENC[AES256_GCM,data:SsQMoBzwVdxp,iv:SkwYMhn1wEbowIAcGMNkJn0tjADDlfSrALJ1OU5Ixcg=,tag:B/oCgK1yRfneiF2tFgwSww==,type:str]
        restart: ENC[AES256_GCM,data:QXrRXp6LssjSQQT+Hxc=,iv:WtYlupBrywt74LlTTy+Mw4zIcA2o3I+mK170Y+iwQcA=,tag:L+INgg+6uT3bTs59Jji/EQ==,type:str]
        secrets:
            - source: ENC[AES256_GCM,data:OMgRj7t7NTAPUyo=,iv:6yjUVFong+jQVvxncPCq7riZSn3b27jePv68MQCPC1A=,tag:XQy2QSZO8U5OKx/EY+MszQ==,type:str]
              target: ENC[AES256_GCM,data:oIZ3BWWjWJnPMC6iBz905g==,iv:dajO8VKPFzWdmHxHeIwvc1v6rYvu2RMV5ebCrIkwBbc=,tag:A0MK8Fr1BarS/rWUE7gkxg==,type:str]
            - source: ENC[AES256_GCM,data:Ydwtrf0fOtbI/Q==,iv:L140nWjZgVJ9n0W8texx2UuTKuF36s0VhQYyfGgV89c=,tag:wIZt2I/dtatJYRikeQMl3w==,type:str]
              target: ENC[AES256_GCM,data:2oUZC2oGihG+ZqUTB2sj,iv:xJNodSMc5G+aJk+mnCGRGX3pOVTBFEvx6+VsKeADCk0=,tag:zQ6hY0iPT/oAnmXr92dVrg==,type:str]
        volumes:
            - ENC[AES256_GCM,data:oyjrN48o5AOElhhLjoLIvJBY8+jhY+qmLW6Uc3pBUtkCstJSXWHv6e4jrRU=,iv:pgCi/dRkHp1KUKU3O3CohunL459aAmka/+3lxUiiFps=,tag:BYI1yym/Aadn3Jh35wKV5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNGxqRGVLQWhPcVdMVGMr
            dHBQdWoyOG1ncUJHU2kwRWJYOEpRZkpsTkY0CjJRRU5VTzlUUE9HWDFjaHk5cFJI
            dmdiVENhK3NzMnp5Q3NUbVFyTVpWN0UKLS0tIDFXMlBhZHJZMzl0b0NKYklxakhN
            amd6WVlURHY0SjI0M3orbmV5ZDVidVEKLJRA5X36PdgrGVFo6OPJB9+juNmAPg0Y
            Ldr/Gcl1iuj1YEc2jDYW41+2MhVxEQmcL17VG7SdCvQbT3wP8qdoTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1heqmzgcj5d2fe7c96leq9kqm6vc4mqhpn94d685q3px9utzlq98q2tv268
    lastmodified: "2026-07-28T23:32:26Z"
    mac: ENC[AES256_GCM,data:YI24Zi38CnfBZOunI32cy9crxIBTd4a00wysowrjWOiUQCouthuGVxPADBxZuceKNfZDPzi7azehC95fZJU0X8C6Jmdf3xGuS9NfsXnxCRItSv9mv5S24UGf/LQLfeF6E0sDUqtjJW3gqvhF8AzPEPRG1zf5l6ux7qGgy0SUwUU=,iv:kfWQ2f+fFaIUyrIz7nQ4PVmKdtLaBAKPKMX38mBUOLo=,tag:mbQz/y++YFIg585xwDIdcg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
