secrets:
    dozzle_cert:
        file: ENC[AES256_GCM,data:fEovSHnouIBMo/zMV2JUAp8=,iv:APHFgtJzk4zVA67sxsQhsFZ3H5Uz0FHOD7dd9jsgUtU=,tag:Y+usMkkS/7g5vEeQZi/vLg==,type:str]
    dozzle_key:
        file: ENC[AES256_GCM,data:OyaITcVFdl4OWqKcOUcMNw==,iv:5pSisuRZEmj5IPkmOeGGI07nG8JDdLnAWhbAp11aKrU=,tag:gTWdoKq3LwfNauu8ap53xQ==,type:str]
services:
    dozzle-agent:
        command: ENC[AES256_GCM,data:s1M+GeQ=,iv:sFEIbwIhIxRL4+iWAZMxtUgdCHclKRI0Te1wMnJnGCo=,tag:kpfQF5bGIJhu3KtSGXqpnQ==,type:str]
        environment:
            DOZZLE_HOSTNAME: ENC[AES256_GCM,data:0m5E/ert,iv:rHLBy8qa25Ylv356FqmkWaWm/r0nBlLb0Dmz7A1jQVk=,tag:X52vQs8sabD+qT+ogquuAA==,type:str]
        image: ENC[AES256_GCM,data:PSIQGW64phUEfLjVGzXpBSAkmKlSmw==,iv:QvTLobTXnJkyVkdPCEo8yOvuC7ky0mu758kGcUrjEMg=,tag:ZbJT2lqZSJ1b2KtcZwpnnA==,type:str]
        ports:
            - ENC[AES256_GCM,data:xWEhndbv7R9h,iv:WPMs8uiUOU5rARHSIfS3HMns4peuzvUnMcnbPMYQ6Kg=,tag:4EcOHT2mD9ceaCGd9CYr8g==,type:str]
        restart: ENC[AES256_GCM,data:euvj/sZNzveVdn7GT+U=,iv:tH3QxGDu4CT3yUwBIMkpugGN6NcWjQKO1xkU5Q8B6qI=,tag:0Syc336obj5gHx7Qm+49GQ==,type:str]
        secrets:
            - source: ENC[AES256_GCM,data:6mj331gVMeF02qk=,iv:6ryP1DM6tSLUh5WvW81ptuhyh3CDCfQ7Z79TnvVwVW4=,tag:P1CdyU8Ttz4ZUfiaiSGPRg==,type:str]
              target: ENC[AES256_GCM,data:hiOgSc+ewaja56C9GFcmHg==,iv:Wbel3EEqYSgC5O63JqNomUEcl2NVIh5CfJQ3nPPy1OM=,tag:E26YmVS+q6dhER3uPtvqaA==,type:str]
            - source: ENC[AES256_GCM,data:11/zNB8OuqCNGQ==,iv:oQRwxXDBcPSBl6IKyRIPfEG/oBCdL1UQP2ZOPqtNtQs=,tag:zQD12nOu95hPy+5IU1IHvQ==,type:str]
              target: ENC[AES256_GCM,data:cuFZJR/NHcMHmeD0ZcYZ,iv:Uou+03CGP9xXxutJykdfNyygOQFA20BcLcEEZU0gm1A=,tag:+C6nM+CbTLE9qku8aP63HQ==,type:str]
        volumes:
            - ENC[AES256_GCM,data:+GdiM7k6JeBwA93vbgzxZ5nrfuIAhA7S73bfkGyAhyGwFQIIJUiLEMH1cFA=,iv:EMDjvfDHwRPUhAdEqWCa92XUf8zp0TcmUGSiEK2GmYk=,tag:1M1CrB/5fwFvnPPoTLSY/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0REdqZE1FcHprOUlGeGlG
            a0pyTnJPeEU0Y0JWSlFBZ3VWYUJtWkl3cmdvCktVQWxIV2xnRG4veDhoMUZGQ0xR
            ZnkrUk4vV1FwNWkwajRFMzYyL2RsbzgKLS0tIGNhNW5venovOHVNRS9mYWVWeTB5
            TVZlQjFVeWIyMEQ3RThaQnE2WXorcVUKpBRcQWiIyzPr9cVlt2vGIrrn7PIoGuby
            u/fLOphbJ4zvBzDy9m8M0/XUns6E5NFN0UJx+woLO9rktFIsyajkMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1heqmzgcj5d2fe7c96leq9kqm6vc4mqhpn94d685q3px9utzlq98q2tv268
    lastmodified: "2026-07-26T22:33:28Z"
    mac: ENC[AES256_GCM,data:fGmaSNpihVrITSBxgkxErpdnMyZDcevOIiozV6Px6H1rHnZOl8DCgm4m/vDbC20dQqmDgIhwHbbvW1JaUJyDVlFC52K0Hmda9r03pCYblEgQl1qh241tqGn2G8tfel5sjOPpbR8pzTrXoNrlwVc1d9WMZSsySHvkOwV0nfP5pY8=,iv:P/nsiYB54MiTsL+eDKqpXFE1CR6gC13CAWJfkdZMtJ8=,tag:ZP89YOX8ECs1hgBGdgq/SA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
