services:
  openspeedtest:
    environment:
      CHANGE_CONTAINER_PORTS: "True"
      HTTP_PORT: 30116
    image: openspeedtest/latest:v2.0.6
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.openspeedtest-buffering.buffering.maxrequestbodybytes: "36700160"
      traefik.http.routers.openspeedtest-http.entrypoints: web
      traefik.http.routers.openspeedtest-http.middlewares: internal-only@docker,redirect-to-https@docker
      traefik.http.routers.openspeedtest-http.rule: Host(`openspeedtest.hsp.au.excloo.dev`)
      traefik.http.routers.openspeedtest-http.service: openspeedtest
      traefik.http.routers.openspeedtest.entrypoints: websecure
      traefik.http.routers.openspeedtest.middlewares: internal-only@docker,openspeedtest-buffering@docker
      traefik.http.routers.openspeedtest.rule: Host(`openspeedtest.hsp.au.excloo.dev`)
      traefik.http.routers.openspeedtest.service: openspeedtest
      traefik.http.routers.openspeedtest.tls.certresolver: cloudflare
      traefik.http.services.openspeedtest.loadbalancer.server.port: "30116"
    restart: unless-stopped
