services:
  oauth2-proxy:
    environment:
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST: "true"
      OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST_LIMIT: 10
      OAUTH2_PROXY_COOKIE_DOMAINS: .hsp.au.excloo.dev
      OAUTH2_PROXY_COOKIE_SAMESITE: lax
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_COOKIE_SECURE: "true"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://id.excloo.com
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: Excloo ID
      OAUTH2_PROXY_REDIRECT_URL: https://oauth2-proxy.hsp.au.excloo.dev/oauth2/callback
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_SILENCE_PING_LOGGING: "true"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_TRUSTED_PROXY_IPS: 127.0.0.1/32,::1/128,172.16.0.0/12,100.77.227.122/32
      OAUTH2_PROXY_UPSTREAMS: static://202
      OAUTH2_PROXY_WHITELIST_DOMAINS: .hsp.au.excloo.dev
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.15.3-alpine
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.oauth2-forward-auth.forwardauth.address: http://127.0.0.1:4180
      traefik.http.middlewares.oauth2-forward-auth.forwardauth.authResponseHeaders: X-Auth-Request-Email,X-Auth-Request-Preferred-Username,X-Auth-Request-User
      traefik.http.middlewares.oauth2-forward-auth.forwardauth.trustForwardHeader: "true"
      traefik.http.routers.oauth2-proxy-http.entrypoints: web
      traefik.http.routers.oauth2-proxy-http.middlewares: internal-only@docker,redirect-to-https@docker
      traefik.http.routers.oauth2-proxy-http.rule: Host(`oauth2-proxy.hsp.au.excloo.dev`)
      traefik.http.routers.oauth2-proxy-http.service: oauth2-proxy
      traefik.http.routers.oauth2-proxy.entrypoints: websecure
      traefik.http.routers.oauth2-proxy.middlewares: internal-only@docker
      traefik.http.routers.oauth2-proxy.rule: Host(`oauth2-proxy.hsp.au.excloo.dev`)
      traefik.http.routers.oauth2-proxy.service: oauth2-proxy
      traefik.http.routers.oauth2-proxy.tls.certresolver: cloudflare
      traefik.http.services.oauth2-proxy.loadbalancer.server.port: "4180"
    ports:
      - 127.0.0.1:4180:4180
    restart: unless-stopped
